### ISSUE TITLE
Ghost Texture

### ISSUE THREAD

**Issue by czw0078** [daniilidis-group/neural_renderer#11]
Hi, I test this wonderful renderer with a [coffee mug model](http://auburn.edu/~czw0078/issue_07_31/mug_model_example.zip) and it looks great! The model is built by software [Blender](https://www.blender.org/) by myself. 

I use [this script](http://auburn.edu/~czw0078/issue_07_31/test_mug.py) run on PyTorch version to load the coffee mug and get this
![](http://auburn.edu/~czw0078/issue_07_31/pytorch_version_mug.png)

Nice rendering work!

However, when I compare it with below result from OpenGL renderer, I realize that some "ghost" textures on the object on above neural renderer result:(the flip of texture is no big issue)
![](http://auburn.edu/~czw0078/issue_07_31/opengl_version_mug.png)

So I explored a little bit and also found the phenomenon on other white background objects(Both Chainer version and PyTorch version) when I test other models. 

Any idea how to fix this bug?

**Comment by nkolot** [comment]
I suspect that it might have to do with the fact that the renderer does not support vertex normals when   loading an .obj file. So most likely is an .obj loading issue and not a renderer bug.

Can you test with an obj file that does not have vertex normals and see if you are getting the desired results? Another thing to try is to load the mesh using neural_renderer, save it with save_obj and try to renderer it with OpenGL to see if it renders properly.

I'm quite busy and I won't have too much time this week to do proper tests.

**Comment by czw0078** [comment]
> Can you test with an obj file that does not have vertex normals and see if you are getting the desired results? Another thing to try is to load the mesh using neural_renderer, save it with save_obj and try to renderer it with OpenGL to see if it renders properly.

Good strategy to identify the bug. I try it. Thank you for the advice!

**Comment by czw0078** [comment]
Hi, thank you for the debugging advice. I follow your guide and tried what you suggested, and here is my brief: (Hopes it can help you narrow down your search of the solution)😄 

(1). First, the "save_obj.py" is broken (so I use Chainer version instead). When I try to use the PyTorch version of save_obj.py, I get a pure white object and has no textures on the saved obj. I look into the save_obj.py source code and [see this line](https://github.com/daniilidis-group/neural_renderer/blob/55a05a28d70e278edd9e04b812b27e747486ccaf/neural_renderer/save_obj.py#L29). I guess the save_obj.py is still incomplete? This line of code is just "whiten" everything.

But let's put (1) aside for now.

(2). Since the PyTorch version does not work, I use the Chainer version save_obj function to save the loaded mesh(coffee mug), and here is the result of the saved model looks like in the OpenGL(Mac Preview):
![figure_5](https://user-images.githubusercontent.com/21988239/44507042-b3536300-a66e-11e8-9735-204eecbbfa0b.png)
The result looks correct, except the blurry (due to the texture_size_out=16 not as large as the size of textures tensor texture_size x texture_size x texture_size ) and the minor flipping issue of renderer inconsistency. But we do not see any ghost problem here.

Here is my simple Chainer code as reference

```
import chainer
import numpy as np
import scipy.misc
import neural_renderer

renderer = neural_renderer.Renderer()

vertices, faces, textures = neural_renderer.load_obj( '/home/chengfei/projects/test_coffe_mug/straight.obj', load_texture=True, texture_size=16)

neural_renderer.save_obj('/home/chengfei/projects/test_coffe_mug/chainer_save.obj', vertices, faces, textures)
```

(3).  Here is the result sof the same model looks like in PyTorch version of neural renderer (with different setting of texture_size)


texture_size = 4
![iterm2 04 out3](https://user-images.githubusercontent.com/21988239/44507937-11357a00-a672-11e8-94f3-c0df495d64ad.png)
texture_size = 8
![iterm2 08 out3](https://user-images.githubusercontent.com/21988239/44507944-1d213c00-a672-11e8-806c-b553579a9607.png)
texture_size = 16
![iterm2 16 out3](https://user-images.githubusercontent.com/21988239/44507954-26120d80-a672-11e8-8102-9b235ed76076.png)

You can notice that the larger the texture_size is, the more sharper the textures look, also the more obvious ghosts appear.  Hope it can gives you some insights on this bug.

(4).  I also investigated your " vertex normals loading" doubt, see code from [this line](https://github.com/daniilidis-group/neural_renderer/blob/55a05a28d70e278edd9e04b812b27e747486ccaf/neural_renderer/load_obj.py#L48) to [that line](https://github.com/daniilidis-group/neural_renderer/blob/55a05a28d70e278edd9e04b812b27e747486ccaf/neural_renderer/load_obj.py#L68). After excuting those lines, if the input is
```
f 4/5/4 10/10/17 11/12/18
```
then v0 = 5, v1 = 10, v2 = 12, the vertex normal after the second slash (see note[1]) not even be readed. So I do not think it is because of vertex normal. 

Based on all above tests (1)~(4), I tend to think it is a renderer bug, not loading problem. What do you think? If it is a "deep" bug that involves the rasterization cuda kernal code(hard to understand), is it possible to fix it? Or we should forward this question to Hiroharu Kato and ask for his help? This bug is annoying on light-colour (especially white) 3d models.

Note [1] from [file format of .obj file](http://paulbourke.net/dataformats/obj/)

>     f  v1/vt1/vn1   v2/vt2/vn2   v3/vt3/vn3 . . .
> 
>     Polygonal geometry statement.
> 
>     Specifies a face element and its vertex reference number. You can
>     optionally include the texture vertex and vertex normal reference
>     numbers.
> 
>     The reference numbers for the vertices, texture vertices, and
>     vertex normals must be separated by slashes (/). There is no space
>     between the number and the slash.
> 
>     v is the reference number for a vertex in the face element. A
>     minimum of three vertices are required.
> 
>     vt is an optional argument.
> 
>     vt is the reference number for a texture vertex in the face
>     element. It always follows the first slash.
> 
>     vn is an optional argument.

**Comment by czw0078** [comment]
I believe the ghost problem is solved now, we can close this issue. I have already sent a pull request. Note: My fix also considered the divided by zero issue.

**Comment by logicsh** [comment]
When I use save_obj.py:
image = image.cpu().numpy()
RuntimeError: CUDA error: an illegal memory access was encountered
I want to ask how to solve this problem.
