### ISSUE TITLE
The install command does not work

### ISSUE THREAD

**Issue by unw9527** [daniilidis-group/neural_renderer#114]
Hello. Thanks for your work.

When I ran `pip install neural_renderer_pytorch` it would always raise a bunch of errors.

The end of the error is like:  

> DeprecatedTypeProperties & type() const {
>                                                     ^
>     error: command 'gcc' failed with exit status 1

Any suggestions on this issue?

**Comment by tcexeexe** [comment]
I have a similar problem. Does anyone have a solution？
