### ISSUE TITLE
Could not load obj correctly.

### ISSUE THREAD

**Issue by qilimk** [daniilidis-group/neural_renderer#12]
Awesome works!! I am trying to load some fancy obj files without image texture, but there is some difference between the result from the preview(Mac app) and this renderer. It looks like could load object correctly, but lose some texture and seems a general problem since it always happened when I tried several models. I show a simple model comparison below which the left side is rendering result and the right side is preview result.
![camaro_comp](https://user-images.githubusercontent.com/31877208/44071066-a7013916-9f4c-11e8-9214-9f4b8a09a415.gif)
The 3d model is downloaded from 3D Warehouse and exported as obj file from the skp file. Here is [obj](https://s3.amazonaws.com/qi-learning-source/ml/render_results/camaro.obj)(1.4MB) and [mtl](https://s3.amazonaws.com/qi-learning-source/ml/render_results/camaro.mtl)(1.8KB) files. 
Could you help me to check this problem? What do you think about it?
Thanks a lot!

**Comment by MilanKolkata** [comment]
Thanks for replying so quickly, I tried to delete all vertex normals lines and its preview is still normal, but result from renderer is also no-changed. Do you think it is because there are too many groups in the obj file?

**Comment by nkolot** [comment]
Have you tried rendering the silhouette only? How do the results look like?

**Comment by MilanKolkata** [comment]
Sorry for ambiguous expression. I didn't render the silhouettes, and I think you are right that the renderer does not support the vertex normals, so I delete all the vertex normals lines and make a new obj file. The result is below.
 
![camaro_no_vn_comp](https://user-images.githubusercontent.com/31877208/44108179-42da53f0-9fbf-11e8-8af7-d5ff899c8485.gif)
Here is the new [obj](https://s3.amazonaws.com/qi-learning-source/ml/render_results/camaro_no_vn.obj) and [mtl](https://s3.amazonaws.com/qi-learning-source/ml/render_results/camaro_no_vn.mtl) files.
The preview result is still different from rendering result.

**Comment by MilanKolkata** [comment]
Thanks so much, I may try some other solutions! If you have any new idea to solve this problem, could you let me know about it?
