### ISSUE TITLE
Too slow on backward computation of silhouettes

### ISSUE THREAD

**Issue by Arthur151** [daniilidis-group/neural_renderer#15]
Thanks for your work.
It costs over 0.1s on only one sample backward computation. As the batch size larger, it significantly slows down my training.
Looking forward to your reply!

**Comment by Arthur151** [comment]
Yes, I have just tried the original Chainer code with human body mesh (about 7000s vertices, 13000 faces, renderer image size 256*256) , the speed is on the same level (more or less) with yours....

**Comment by nkolot** [comment]
I am closing this issue for now.

**Comment by ypflll** [comment]
@Arthur151 Hi, Do you render an smpl model?  I get more than 200ms when rasterize a silhouette, with no back computation. I wonder if something wrong in my code... 
`faces = torch.from_numpy(faces).cuda()
faces = [None,:,:]
ver = torch.from_numpy(ver).cuda()
ver = ver[None,:,:]
faces = nr.vertices_to_faces(ver, faces)
silhouettes = nr.rasterize_silhouettes(faces, 256, True)`

If I use rederer like this (change to c++): https://github.com/YadiraF/PRNet/blob/master/utils/render.py
It only takes several ms.
I wonder if I can speed this up.

**Comment by DragonZzzz** [comment]
@ypflll  Have you solve this problem? I alse render the mesh very slowly.
