### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by nchinaev** [daniilidis-group/neural_renderer#24]
Function `neural_renderer.rasterize` takes approximately 1.1 s to rasterize 10^5 polygons on a Titan GPU.

Is this the expected time, or could it be improved?

**Comment by nkolot** [comment]
Indeed for large meshes the rendering time is very slow, because the "for each pixel" is run in parallel, but every thread iterates over all faces. As far as I know, opendr also is very slow for rendering when you also want gradients.
