### ISSUE TITLE
Ghost texture

### ISSUE THREAD

**Issue by fxia22** [daniilidis-group/neural_renderer#25]
This commit needs to be applied: https://github.com/hiroharu-kato/neural_renderer/commit/310d8b55abc050bd3d0ac1a0c9e6e4cfa6bb3336

**Comment by nkolot** [comment]
Can you make the change and submit a PR?

**Comment by fxia22** [comment]
Sure there you have it #26 :)

**Comment by czw0078** [comment]
@fxia22 FYI: to avoid the wrong gradient (NaN), please look this #27

**Comment by czw0078** [comment]
Right, I test it. The >0 condition prevents the divided by zero problems.

**Comment by fxia22** [comment]
Yes, please merge the other PR instead. Thanks.
