### ISSUE TITLE
Any reason you don't upload to Pypi ?

### ISSUE THREAD

**Issue by Narsil** [daniilidis-group/neural_renderer#31]
It's just an idea but I think you could upload your package to Pypi, no ?

**Comment by nkolot** [comment]
I can do it at some point. I wanted first to fix some of the currently existing issues and maybe clean up some parts of the code as wekk. I tried to change as little as possible from the original repo when reimplementing it in PyTorch to avoid introducing bugs, but I think that some parts should be refactored.

**Comment by Narsil** [comment]
Any directions of what you want to do, in terms of refactoring/bugfixing ? I might be able to help

**Comment by nkolot** [comment]
We can discuss about it after the CVPR deadline. Thanks for offering to help.

**Comment by Narsil** [comment]
I have done some work on my fork where I removed the look/look_at/and K/R projection as I don't think they belong in the renderer.

First of all, the look/look_at ideas present a pretty big non-linearity when the camera goes from elevation0 to elevation 180 (basically the camera flips 180 when going across Up[0, 1, 0] direction).
In OpenGL and other renderers, one manipulates directly rotations and translations, and the look_at paradigm is generally a bad practice IMO.

- I reduced a lot the code size by fusing the different rendering modes.
- I updated all codes and examples towards the new version (one tests was changed to keep the look_at paradigm with just a few lines of code).

All tests are still passing.

- I took 2 patches which seemed better for texture loading and #18 for gradient orientation.

What do you think about that direction ?
