### ISSUE TITLE
Rendered Meshes with Large Faces are Blurry.

### ISSUE THREAD

**Issue by Ailuridae** [daniilidis-group/neural_renderer#32]
The original paper states:

> We use Figure 2 (b) for the forward pass because if we use Figure 2 (d), the color of a face leaks outside of the face. **Therefore, our rasterizer produces the same images as the standard rasterizer**, but it has non-zero gradients.

This is not correct, as meshes with large faces and detailed textures will result in a blurry images. The problem, which was already described in #6, could probably be solved by rewriting the current texture sampling method. What's the reason behind the current implementation?

**Comment by nkolot** [comment]
This repo contains a PyTorch reimplementation of the original repo. It should be more appropriate to ask this question in the original repo. I understand what you are saying, and feel free to implement a different sampling method and submit a PR if you want.
