### ISSUE TITLE
setup.py installation issues

### ISSUE THREAD

**Issue by ghost** [daniilidis-group/neural_renderer#37]
```
neural_renderer/cuda/load_textures_cuda.cpp:37:17: note: in expansion of macro ‘TORCH_EXTENSION_NAME’
 PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
                 ^~~~~~~~~~~~~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
I get the following error when I run sudo python3 setup.py install

CUDA 9.0 
Ubuntu 18.04 
torch 0.4.0
gcc 5.5

**Comment by Myzhencai** [comment]
@ghost Hi, I have the same environment as you does and I install it in anconda but I have the issue:
ERROR: Complete output from command /home/gaofei/anaconda3/envs/dynamic1/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-341qkp51/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-iqbj2wrx --python-tag cp35:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/load_obj.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/rasterize.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/save_obj.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/perspective.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/look_at.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/renderer.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/get_points_from_angles.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/mesh.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/__init__.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/look.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/projection.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/lighting.py -> build/lib.linux-x86_64-3.5/neural_renderer
  copying neural_renderer/vertices_to_faces.py -> build/lib.linux-x86_64-3.5/neural_renderer
  creating build/lib.linux-x86_64-3.5/neural_renderer/cuda
  copying neural_renderer/cuda/__init__.py -> build/lib.linux-x86_64-3.5/neural_renderer/cuda
  running build_ext
  building 'neural_renderer.cuda.load_textures' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/neural_renderer
  creating build/temp.linux-x86_64-3.5/neural_renderer/cuda
  gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include -I/home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/TH -I/home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/gaofei/anaconda3/envs/dynamic1/include/python3.5m -c neural_renderer/cuda/load_textures_cuda.cpp -o build/temp.linux-x86_64-3.5/neural_renderer/cuda/load_textures_cuda.o -DTORCH_EXTENSION_NAME=neural_renderer.cuda.load_textures -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  neural_renderer/cuda/load_textures_cuda.cpp: In function ‘at::Tensor load_textures(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int)’:
  neural_renderer/cuda/load_textures_cuda.cpp:15:79: error: ‘AT_CHECK’ was not declared in this scope
   #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                                                                                 ^
  neural_renderer/cuda/load_textures_cuda.cpp:17:24: note: in expansion of macro ‘CHECK_CUDA’
   #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                          ^
  neural_renderer/cuda/load_textures_cuda.cpp:28:5: note: in expansion of macro ‘CHECK_INPUT’
       CHECK_INPUT(image);
       ^
  In file included from /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/pytypes.h:12:0,
                   from /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/cast.h:13,
                   from /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/attr.h:13,
                   from /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/pybind11.h:43,
                   from /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/torch/torch.h:6,
                   from neural_renderer/cuda/load_textures_cuda.cpp:1:
  neural_renderer/cuda/load_textures_cuda.cpp: At global scope:
  <command-line>:0:37: error: expected initializer before ‘.’ token
  /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/detail/common.h:212:47: note: in definition of macro ‘PYBIND11_CONCAT’
   #define PYBIND11_CONCAT(first, second) first##second
                                                 ^
  neural_renderer/cuda/load_textures_cuda.cpp:37:1: note: in expansion of macro ‘PYBIND11_MODULE’
   PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
   ^
  neural_renderer/cuda/load_textures_cuda.cpp:37:17: note: in expansion of macro ‘TORCH_EXTENSION_NAME’
   PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
                   ^
  <command-line>:0:37: error: expected initializer before ‘.’ token
  /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/detail/common.h:171:51: note: in definition of macro ‘PYBIND11_PLUGIN_IMPL’
       extern "C" PYBIND11_EXPORT PyObject *PyInit_##name()
                                                     ^
  neural_renderer/cuda/load_textures_cuda.cpp:37:1: note: in expansion of macro ‘PYBIND11_MODULE’
   PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
   ^
  neural_renderer/cuda/load_textures_cuda.cpp:37:17: note: in expansion of macro ‘TORCH_EXTENSION_NAME’
   PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
                   ^
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for neural-renderer-pytorch
  Running setup.py clean for neural-renderer-pytorch
Failed to build neural-renderer-pytorch
Installing collected packages: neural-renderer-pytorch
  Running setup.py install for neural-renderer-pytorch ... error
    ERROR: Complete output from command /home/gaofei/anaconda3/envs/dynamic1/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-341qkp51/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l2_e5ncz/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/load_obj.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/rasterize.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/save_obj.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/perspective.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/look_at.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/renderer.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/get_points_from_angles.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/mesh.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/__init__.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/look.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/projection.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/lighting.py -> build/lib.linux-x86_64-3.5/neural_renderer
    copying neural_renderer/vertices_to_faces.py -> build/lib.linux-x86_64-3.5/neural_renderer
    creating build/lib.linux-x86_64-3.5/neural_renderer/cuda
    copying neural_renderer/cuda/__init__.py -> build/lib.linux-x86_64-3.5/neural_renderer/cuda
    running build_ext
    building 'neural_renderer.cuda.load_textures' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/neural_renderer
    creating build/temp.linux-x86_64-3.5/neural_renderer/cuda
    gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include -I/home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/TH -I/home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/gaofei/anaconda3/envs/dynamic1/include/python3.5m -c neural_renderer/cuda/load_textures_cuda.cpp -o build/temp.linux-x86_64-3.5/neural_renderer/cuda/load_textures_cuda.o -DTORCH_EXTENSION_NAME=neural_renderer.cuda.load_textures -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    neural_renderer/cuda/load_textures_cuda.cpp: In function ‘at::Tensor load_textures(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int)’:
    neural_renderer/cuda/load_textures_cuda.cpp:15:79: error: ‘AT_CHECK’ was not declared in this scope
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                                                                                   ^
    neural_renderer/cuda/load_textures_cuda.cpp:17:24: note: in expansion of macro ‘CHECK_CUDA’
     #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                            ^
    neural_renderer/cuda/load_textures_cuda.cpp:28:5: note: in expansion of macro ‘CHECK_INPUT’
         CHECK_INPUT(image);
         ^
    In file included from /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/pytypes.h:12:0,
                     from /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/cast.h:13,
                     from /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/attr.h:13,
                     from /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/pybind11.h:43,
                     from /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/torch/torch.h:6,
                     from neural_renderer/cuda/load_textures_cuda.cpp:1:
    neural_renderer/cuda/load_textures_cuda.cpp: At global scope:
    <command-line>:0:37: error: expected initializer before ‘.’ token
    /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/detail/common.h:212:47: note: in definition of macro ‘PYBIND11_CONCAT’
     #define PYBIND11_CONCAT(first, second) first##second
                                                   ^
    neural_renderer/cuda/load_textures_cuda.cpp:37:1: note: in expansion of macro ‘PYBIND11_MODULE’
     PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
     ^
    neural_renderer/cuda/load_textures_cuda.cpp:37:17: note: in expansion of macro ‘TORCH_EXTENSION_NAME’
     PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
                     ^
    <command-line>:0:37: error: expected initializer before ‘.’ token
    /home/gaofei/anaconda3/envs/dynamic1/lib/python3.5/site-packages/torch/lib/include/pybind11/detail/common.h:171:51: note: in definition of macro ‘PYBIND11_PLUGIN_IMPL’
         extern "C" PYBIND11_EXPORT PyObject *PyInit_##name()
                                                       ^
    neural_renderer/cuda/load_textures_cuda.cpp:37:1: note: in expansion of macro ‘PYBIND11_MODULE’
     PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
     ^
    neural_renderer/cuda/load_textures_cuda.cpp:37:17: note: in expansion of macro ‘TORCH_EXTENSION_NAME’
     PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
                     ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/gaofei/anaconda3/envs/dynamic1/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-341qkp51/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l2_e5ncz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-341qkp51/
