### ISSUE TITLE
Windows Anaconda support?

### ISSUE THREAD

**Issue by GritBear** [daniilidis-group/neural_renderer#38]
I'm trying to use this package but running into compilation errors. Has anyone tried to make it run on windows anaconda?

The errors for me are:
Anaconda3\lib\site-packages\torch\lib\include\torch\csrc\api\include\torch/torch.h(7): fatal error C1021: invalid preprocessor command 'warning'

**Comment by nkolot** [comment]
We do not support Windows.

**Comment by sxhzju** [comment]
> I'm trying to use this package but running into compilation errors. Has anyone tried to make it run on windows anaconda?
> 
> The errors for me are:
> Anaconda3\lib\site-packages\torch\lib\include\torch\csrc\api\include\torch/torch.h(7): fatal error C1021: invalid preprocessor command 'warning'

![image](https://user-images.githubusercontent.com/33959089/61374106-17f25e80-a8ce-11e9-88ee-901b4dddb7d1.png)
after a long time struggling, I built this on windows successfully...

for your problem which I met also, you just need to comment out `#warning` in **torch.h(7)** and I suppose that is cuz MSVC complier does not support that grammer.. 

then you may encounter another problem but you can just google and that will fix dude..

god bless us..
