### ISSUE TITLE
How to save as .obj ?

### ISSUE THREAD

**Issue by jay-thakur** [daniilidis-group/neural_renderer#49]
Hi,

I used this code to save as .obj-
```

import chainer
import numpy as np
import scipy.misc
import neural_renderer

renderer = neural_renderer.Renderer()

vertices, faces, textures = neural_renderer.load_obj( '/home/user/jay/straight.obj', load_texture=True, texture_size=16)

neural_renderer.save_obj('/home/user/jay/chainer_save.obj', vertices, faces, textures)

```
But getting error at [this assert](https://github.com/daniilidis-group/neural_renderer/blob/master/neural_renderer/save_obj.py#L42) So changed [this line](https://github.com/daniilidis-group/neural_renderer/blob/master/examples/example3.py#L25-L26) to 

```
self.register_buffer('vertices', vertices[:, :])
self.register_buffer('faces', faces[:, :])
```

But facing issue in renderer.py. So i changed [the code](https://github.com/daniilidis-group/neural_renderer/blob/master/neural_renderer/renderer.py#L92) with below line.

```
faces = torch.cat((faces, faces[:, list(reversed(range(faces.shape[-1])))]), dim=1).detach()
```

Then i was getting error in [vertices_to_faces.py](https://github.com/daniilidis-group/neural_renderer/blob/master/neural_renderer/vertices_to_faces.py#L10) so i changed below vertices & faces assert to 2.
```
assert (vertices.ndimension() == 2)
assert (faces.ndimension() == 2)
```
But I am getting error at [this line](https://github.com/daniilidis-group/neural_renderer/blob/master/neural_renderer/vertices_to_faces.py#L12)
```assert (vertices.shape[0] == faces.shape[0]) ```because
vertices.shape[0] = 34817
faces.shape[0] = 69630.

Where am i doing wrong ? Could you please help me to fix this.

**Comment by nkolot** [comment]
You need to add a dummy batch dimension, so vertices will be (1,34817,3) and faces (1,69630,3).
