### ISSUE TITLE
error: ‘AT_CHECK’ was not declared in this scope

### ISSUE THREAD

**Issue by Pinnh** [daniilidis-group/neural_renderer#87]
In higher version torch , that AT_CHECK function is changed to TORCH_CHECK

**Comment by hamaadtahir** [comment]
how to solve this issue with pytorch 0.4.0 and python3?

**Comment by Pinnh** [comment]
so simple ,upgrade your pytorch version

**Comment by hamaadtahir** [comment]
to which one?

**Comment by IceClear** [comment]
pytorch1.2.0+cuda10.0 works

**Comment by jugwangjin** [comment]
I'm using pytorch 1.9.1+cuda11.1 and changing AT_CHECK to TORCH_CHECK  actually worked. Thank you for your help.
